[workspace]
members = ["crates/strenor-store", "crates/strenor-node"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
authors = ["Hepein Oficial (Brashkie)"]
repository = "https://github.com/Brashkie/strenor"

[profile.release]
lto = true
opt-level = 3
strip = "symbols"
